name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # This checks out the latest code from the repository
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | bash  # Using bash instead of sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}  # Logs into Postman CLI using the API key from secrets
      - name: Run API tests
        run: postman collection run "40953313-ab545157-b1f1-4477-bc59-3b66ef02cd2e"  # Run the API tests using the Postman collection ID

